# Production environment that can be used directly on Heroku. 
# Differences to stage include:
#  - App files are copied into the container, no volume mounting
#  - Gunicorn is run directly



FROM airladon/pynode:python3.7.3-node12.1.0-npm6.9.0-docker-heroku

WORKDIR /opt/app


ADD requirements.txt .
RUN pip install --no-cache-dir -q -r requirements.txt



RUN mkdir app
ADD containers/prod/Procfile .
ADD containers/prod/runtime.txt .
ADD containers/prod/wsgi.py .
ADD app/. app/.
RUN mkdir repo
RUN mkdir logs
# RUN rm -rf /opt/app/app/static/src

# RUN apt-get update && \
#	   apt-get -y install git


RUN useradd -m myuser
RUN chown myuser app
RUN chown myuser logs
RUN chown myuser repo
RUN chown myuser app/app/app.db
RUN chmod 666 app/app/app.db
USER myuser


CMD gunicorn --bind 0.0.0.0:$PORT --log-file=/opt/app/logs/gunicorn.txt --log-level debug --access-logfile /opt/app/logs/access_log.txt wsgi
